### ISSUE TITLE
Doesn't compile using newer versions of GCC

### ISSUE THREAD

**Issue by agwilt** [slimlogic/uqlx-fork#1]
I just cloned this, ran `make`, and git a million "undefined reference" errors:

cc     -L/usr/X11/lib/ -L/usr/openwin+/lib/ -L/usr/openwin/lib/ -L/usr/X11R6/lib/ -L/usr/X11R5/lib/  -o qm  Init.o general.o instructions_ao.o instructions_pz.o QLtraps.o QL_hardware.o QL_config.o dummies.o vm.o xqlkey.o qmtrap.o uxfile.o QL_serial.o pty.o uqlx_cfg.o QL_files.o QL_driver.o QDisk.o trace.o version.o QLserio.o QL_screen.o QL_poll.o xcodes.o QL_boot.o QL_basext.o QL_cconv.o  iexl_general.o QVFS.o QL_sound.o Xscreen.o QLip.o util.o xc68.o xipc.o script.o mach_exception.o siginfo.o vl.o ide.o block.o x.o xlmain.o xqlmouse.o unixstuff.o  -lX11 -lXext  
iexl_general.o: In function `inl_ReadWord':
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
iexl_general.o:/home/andreas/src/dl/uqlx-fork/memaccess.h:90: more undefined references to `ReadHWWord' follow
iexl_general.o: In function `inl_WriteWord':
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
iexl_general.o: In function `inl_ReadWord':
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
iexl_general.o: In function `inl_WriteWord':
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
iexl_general.o: In function `inl_ReadWord':
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:90: undefined reference to `ReadHWWord'
iexl_general.o: In function `inl_WriteWord':
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
/home/andreas/src/dl/uqlx-fork/memaccess.h:372: undefined reference to `WriteHWWord'
iexl_general.o:/home/andreas/src/dl/uqlx-fork/memaccess.h:372: more undefined references to `WriteHWWord' follow
instructions_ao.o: In function `cmpm_b':
/home/andreas/src/dl/uqlx-fork/instructions_ao.c:1322: undefined reference to `GetFromEA_rb_m3'
instructions_ao.o: In function `cmpm_w':
/home/andreas/src/dl/uqlx-fork/instructions_ao.c:1338: undefined reference to `GetFromEA_rw_m3'
instructions_ao.o: In function `cmpm_l':
/home/andreas/src/dl/uqlx-fork/instructions_ao.c:1356: undefined reference to `GetFromEA_rl_m3'
QL_basext.o: In function `do_fork':
/home/andreas/src/dl/uqlx-fork/QL_basext.c:588: undefined reference to `conv_chunk'
xipc.o: In function `check_connection':
/home/andreas/src/dl/uqlx-fork/xipc.c:252: undefined reference to `conv_chunk'
collect2: error: ld returned 1 exit status
make: *** [Makefile:264: qm] Error 1

**Comment by slimlogic** [comment]
Yes, I have some fixes locally for this, newer version of gcc doesn't like the misuse of inline keyword in uQlx sources. Ill try and remember to check them and push them out this week!

**Comment by agwilt** [comment]
That would be great, thanks!

**Comment by slimlogic** [comment]
Pushed some changes! Really kludges!
